### ISSUE TITLE
Performance Tracker

### ISSUE THREAD

**Issue by Stevenjin8** [istio/ztunnel#616]
Issue to track my perf work.

In no order, a few things I want to do but might not get to (internship ends 8/25):

- [x] add criterion benchmarks for establishing HBONE connection now that we pool H2
- [ ] #110 implementing the `poll_write`
- [x] flushing out my e2e test script that uses netperf.
- [x] Stare at Wireshark/strace/flame graphs and hope for inspiration
- [ ] Figure out why criterion benchmarks are so inconsistent.
